name: Aggregit

on:
  schedule:
    - cron: "0 0 * * *"

permissions:
  actions: write
  checks: read
  contents: read
  deployments: read
  issues: read
  discussions: read
  packages: none
  pages: read
  pull-requests: read
  security-events: read
  statuses: write

jobs:
  recordMetrics:
    runs-on: ubuntu-latest
    steps:
    - uses: michaeljolley/aggregit@v1
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        project_id: ${{ secrets.project_id }}
        private_key: ${{ secrets.private_key }}
        client_email: ${{ secrets.client_email }}
        firebaseDbUrl: ${{ secrets.firebaseDbUrl }}
